fullname = "PENTAPEN MEDIA UNINC (EXAMPLE DATA)"
type = "Committee"
date_creation = "1970-01-01"
status = "Dormant"
fields = "Media; Journalism; Advertising"
president = "JINYU MENG (a.k.a. MEGABITS)"
secretary = "NERUTHES"
charter_hash = "fc076e021285db327c317965910e8a03aa5614db"
addresses = [
    "https://github.com/pentapen",
    "https://pentapen.com"
]
witness = [
    "https://unincdb.nekostein.com/id/100-0000-0001.pdf"
]
