fullname = "SAMPLE DATA FOR UNINCDB TUTORIAL"
type = "Quasi-LLC"
date_creation = "1970-01-01"
status = "Active"
fields = "Information Technology; Witness Service"
president = "NERUTHES"
secretary = "NERUTHES"
charter_hash = "633251ca87f8b59d1c986eb508d9b22634dacf02"
addresses = [
    "https://github.com/nekostein/unincdb",
]
witness = [
    "https://unincdb.nekostein.com/1970/unincdb-tutorial.pdf"
]

[com.nekostein]
url_stamps = "https://example.com/wiki/article/stamps.html"
