fullname = "SAMPLE DATA FOR UNINCDB TUTORIAL"
type = "Quasi-LLC"
date_creation = "1970-01-01"
status = "Active"
fields = "Information Technology; Notary Service"
president = "NERUTHES"
secretary = "NERUTHES"
charter_hash = "bf89e7a50ff7baeff81a4216a32fa616858e8723"
addresses = [
    "https://github.com/nekostein/unincdb",
]
notary = [
    "https://unincdb.nekostein.com/1970/unincdb-tutorial.pdf"
]
