fullname = "SAMPLE DATA FOR UNINCDB TUTORIAL"
type = "Quasi-LLC"
date_creation = "1970-01-01"
status = "Dormant"
fields = "Information Technology; Witness Service"
president = "NERUTHES"
secretary = "NERUTHES"
charter_hash = "420579b428772da3e4498179ade1c0b6d2901d6b"
addresses = [
    "https://github.com/nekostein/unincdb",
]
witness = [
    "https://unincdb.nekostein.com/id/100-0000-0002.pdf"
]

[com.nekostein]
url_stamps = "https://example.com/wiki/article/stamps.html"
