fullname = "SAMPLE DATA FOR UNINCDB TUTORIAL"
type = "Quasi-LLC"
date_creation = "1970-01-01"
status = "Active"
fields = "Information Technology; Notary Service"
president = "NERUTHES"
secretary = "NERUTHES"
charter_hash = "5e4f469eb1efde10b9bea43004c9c5937de81c7c"
addresses = [
    "https://github.com/nekostein/unincdb",
]
notary = [
    "https://unincdb.nekostein.com/1970/unincdb-tutorial.pdf"
]
