fullname = "SAMPLE DATA FOR UNINCDB TUTORIAL"
type = "Quasi-LLC"
date_creation = "1970-01-01"
status = "Active"
fields = "Information Technology; Witness Service"
president = "NERUTHES"
secretary = "NERUTHES"
charter_hash = "67c3be594d7f389db15dfdd03e982b0789dd36d7"
addresses = [
    "https://github.com/nekostein/unincdb",
]
witness = [
    "https://unincdb.nekostein.com/1970/unincdb-tutorial.pdf"
]
