fullname = "SHINONOME TELECOMMUNICATION NETWORK UNINC"
type = "Quasi-LLC"
date_creation = "2017-11-06"
status = "Active"
fields = "Information Technology; Telecommunication"
president = "CATTEN LINGER"
secretary = "CATTEN LINGER"
charter_hash = "b263a79f4268dbc5658d588e49652ea84b83ffab"
addresses = [
    "https://shinonometn.com",
]
witness = [
    "https://unincdb.nekostein.com/2017/shinonometn.pdf"
]


[upstream]
toml = "https://pub-714f8d634e8f451d9f2fe91a4debfa23.r2.dev/unincdb/d06542b2736a1a09d7ed0dd7/UNINC.toml"
charter = "https://pub-714f8d634e8f451d9f2fe91a4debfa23.r2.dev/unincdb/09facf393e60caa30c75a48f/Charter.md"
appendix = "https://pub-714f8d634e8f451d9f2fe91a4debfa23.r2.dev/unincdb/f3e67438ddf59552f05cff2f/Appendix.md"
